#!/usr/bin/env python3
"""Persistent supervisor — drop-in replacement for supervisor.sh for ONE agent slot.

Launch from tmux exactly like the old bash supervisor:

    python3 src/persistent_supervisor.py <team-dir> <role> <slot> <role-prompt-file> <perm-mode> <model> <provider>

This supervisor:
  - Loads previous state from SQLite on startup
  - Subscribes to the event bus for its team+role
  - Falls back to legacy `bd ready` polling when no events arrive
  - Persists iteration count, scratchpad, and accumulated context
  - Auto-recovers from crashes (releases stale claims, resumes loop)

The old bash supervisor (generated by `bin/cto start`) is stateless:
every iteration re-reads the role prompt from scratch and loses all
context.  This version keeps state in `.cto/state/agent_state.db`.
"""
from __future__ import annotations

import signal
import sys
from pathlib import Path

from agent_process import AgentConfig, AgentProcess


def main() -> int:
    if len(sys.argv) < 7:
        print(
            "usage: persistent_supervisor.py <team-dir> <role> <slot> "
            "<role-prompt-file> <perm-mode> <model> [<provider>]",
            file=sys.stderr,
        )
        return 2

    team_dir = Path(sys.argv[1])
    role = sys.argv[2]
    slot = sys.argv[3]
    role_prompt = Path(sys.argv[4])
    perm_mode = sys.argv[5]
    model = sys.argv[6]
    provider = sys.argv[7] if len(sys.argv) > 7 else "claude"
    team = team_dir.name

    config = AgentConfig(
        team=team,
        role=role,
        slot=slot,
        team_dir=team_dir,
        role_prompt_path=role_prompt,
        model=model,
        agent_provider=provider,
        permission_mode=perm_mode,
    )

    proc = AgentProcess(config)

    def _on_signal(signum: int, _frame: object) -> None:
        print(f"[{slot}] caught signal {signum}, shutting down...", flush=True)
        proc.stop()

    signal.signal(signal.SIGINT, _on_signal)
    signal.signal(signal.SIGTERM, _on_signal)

    proc.run()
    return 0


if __name__ == "__main__":
    sys.exit(main())
